"""Input/Output schema definitions for UCE model.

Inherits from core.model_io.ModelIO to provide automatic device management,
gradient detachment, and dictionary-like access.
"""

from __future__ import annotations

from dataclasses import dataclass

from torch import Tensor

from perturblab.core.model_io import ModelIO

__all__ = [
    "UCEInput",
    "UCEOutput",
    "UCEPredictInput",
    "UCEPredictOutput",
]


@dataclass(kw_only=True)
class UCEInput(ModelIO):
    """Container for UCE model inputs.

    This class encapsulates the raw features required for the UCE encoder-decoder
    architecture. By using this schema, the forward pass signature remains
    consistent regardless of internal feature changes.

    Attributes:
        src: The gene expression token sequence.
            Shape: (seq_len, batch_size, token_dim).
            Note: Follows PyTorch Transformer default (sequence-first).
        mask: The padding mask indicating valid tokens.
            Shape: (batch_size, seq_len).
            Values: 1 for valid tokens, 0 for padding.
    Note:
        All fields must be specified as keyword arguments due to dataclass inheritance constraints.
        Example: UCEInput(field1=..., field2=...)
    """

    src: Tensor
    mask: Tensor


@dataclass(kw_only=True)
class UCEOutput(ModelIO):
    """Container for UCE model outputs.

    Holds the latent representations generated by the UCE model and
    optional predictions.

    Attributes:
        cell_embedding: Normalized cell-level embedding (CLS token).
            Shape: (batch_size, output_dim).
        gene_embeddings: Per-gene context embeddings from the decoder.
            Shape: (seq_len, batch_size, output_dim).
        gene_expression_preds: Predicted expression values.
            Only present if the full prediction pipeline is executed.
            Shape: (batch_size, num_genes) or None.
    Note:
        All fields must be specified as keyword arguments due to dataclass inheritance constraints.
        Example: UCEOutput(field1=..., field2=...)
    """

    cell_embedding: Tensor
    gene_embeddings: Tensor
    gene_expression_preds: Tensor | None = None


@dataclass(kw_only=True)
class UCEPredictInput(ModelIO):
    """Container for UCE predict inputs.

    Features passed specifically to the prediction head. Consolidating these
    into a schema allows the predictor to be decoupled from the encoder.

    Attributes:
        cell_embedding: Normalized cell-level embedding (CLS token).
            Shape: (batch_size, output_dim).
        gene_embeddings: Per-gene context embeddings from the decoder.
            Shape: (seq_len, batch_size, output_dim).
        mask: Optional padding mask for the gene embeddings.
            Shape: (batch_size, seq_len).
    Note:
        All fields must be specified as keyword arguments due to dataclass inheritance constraints.
        Example: UCEPredictInput(field1=..., field2=...)
    """

    cell_embedding: Tensor
    gene_embeddings: Tensor
    mask: Tensor | None = None


@dataclass(kw_only=True)
class UCEPredictOutput(ModelIO):
    """Container for UCE predict outputs.

    Attributes:
        gene_expression_preds: Predicted gene expression values.
            Shape: (batch_size, num_genes).
    Note:
        All fields must be specified as keyword arguments due to dataclass inheritance constraints.
        Example: UCEPredictOutput(field1=..., field2=...)
    """

    gene_expression_preds: Tensor
