"""Input/Output schema definitions for GEARS model.

Inherits from core.model_io.ModelIO to provide automatic device management,
gradient detachment, and dictionary-like access.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from torch import Tensor

from perturblab.core.model_io import ModelIO

__all__ = [
    "GEARSInput",
    "GEARSOutput",
]


@dataclass(kw_only=True)
class GEARSInput(ModelIO):
    """Container for GEARS model inputs.

    This class encapsulates the features required for GEARS perturbation prediction.
    By using this schema, the forward pass signature remains consistent regardless
    of internal changes.

    Args:
        gene_expression (Tensor):
            Gene expression values for all nodes in the batch.
            Shape: (num_graphs * num_genes,) or (batch_size, num_genes).
        pert_idx (list[list[int]] | Tensor):
            Perturbation indices for each graph in the batch.
            Shape: (num_graphs, num_perts_per_graph).
            Use -1 or empty list for no perturbation (control condition).
        graph_batch_indices (Optional[Tensor], optional):
            Batch assignment tensor indicating which graph each node belongs to.
            Required for torch_geometric format when processing multiple graphs.
            Shape: (num_graphs * num_genes,).
            If None, assumes batch_size=1.
    Note:
        All fields must be specified as keyword arguments due to dataclass inheritance constraints.
        Example: GEARSInput(field1=..., field2=...)
    """

    gene_expression: Tensor
    pert_idx: list | Tensor
    graph_batch_indices: Optional[Tensor] = None


@dataclass(kw_only=True)
class GEARSOutput(ModelIO):
    """Container for GEARS model outputs.

    Holds the predicted gene expression and optional uncertainty estimates
    generated by the GEARS model.

    Args:
        predictions (Tensor):
            Predicted gene expression values after perturbation.
            Shape: (num_graphs, num_genes) or (batch_size, num_genes).
        log_variance (Optional[Tensor], optional):
            Log variance for uncertainty quantification.
            Only present if uncertainty mode is enabled in config.
            Shape: (num_graphs, num_genes) or (batch_size, num_genes).
    Note:
        All fields must be specified as keyword arguments due to dataclass inheritance constraints.
        Example: GEARSOutput(field1=..., field2=...)
    """

    predictions: Tensor
    log_variance: Optional[Tensor] = None
